### PR TITLE
add blockless version. closes #8

### LINKED ISSUE #8: [FEATURE] - Support Ember.SelectView style API
The advantage of supporting the old API is that applications migrating from select view to x-select can do so with basically a search and replace.

### PR DESCRIPTION
**Pull request by miguelcobain**
This is working in my app!

Tests and README update still missing.

### CODE REVIEW

**Comment by miguelcobain** [comment]
Just fixed an edge case. 
Your `content` is "item 1, item 2 and item 3" and you have "item 1" selected.
If you remove item 1 from content, your selection must be cleared (set to null).

**Comment by miguelcobain** [comment]
Any problem with this PR?
How can I help?

**Comment by cowboyd** [comment]
If you could add the tests, I'll go ahead and add the README.

**Comment by miguelcobain** [comment]
Please let me know if the tests are covering everything.

**Comment by cowboyd** [comment]
looks good! :+1:

**Comment by cowboyd** [comment]
thanks @miguelcobain! this has been released as `v1.1.2`

**Pull request merged**
