### PR TITLE
Kiwi/fix deploy

### PR DESCRIPTION
**Pull request by kiwiupover**
a fix for https://github.com/thefrontside/emberx-select/pull/207

### CODE REVIEW

**Comment by kiwiupover** [comment]
@Robdel12 I added your circle config to ember-cli-spinjs and it passed with the latest ember-cli-surge
https://circleci.com/gh/kiwiupover/ember-cli-spinjs/26

**Comment by kiwiupover** [comment]
@Robdel12 however I can't get the tests to run on this PR

**Comment by Robdel12** [comment]
OHHH now _that_ is really interesting! Thank you for taking the time to debug this. I wonder if this is a circle cache issue?

**Comment by Robdel12** [comment]
So I've enabled builds for forked PRs, but for security reasons it won't deploy (since someone could change the circle config to echo env variables, etc). 

I don't have my person computer with me today at work so I'll have to get to this when I get home tonight. Thank you again @kiwiupover!! :D

**Comment by kiwiupover** [comment]
@Robdel12 @cowboyd I updated the circleci config and remove `JOBS=2` and the build passed.

I added caching to config too so CI should be a bit faster too. 

Cheers
Dave

**Comment by kiwiupover** [comment]
@Robdel12 ping

**Pull request merged**
