### PR TITLE
- add name to attribute bindings to specify a form element name

### PR DESCRIPTION
**Pull request by enspandi**

### CODE REVIEW

**Comment by jonkoops** [comment]
@enspandi Could you perhaps include the additional attributes discussed in #11 to your pull request?

**Comment by enspandi** [comment]
Just added the remaining attributes: autofocus, form, required, size

**Comment by jonkoops** [comment]
Looks good to me. @cowboyd think we can get this merged?

**Comment by cowboyd** [comment]
Looks great! Once we get some tests wrapped around this, merge is a go.

**Comment by enspandi** [comment]
Sorry for the delay. I hope the tests are fine; wasn't sure to check for more than just the attribute binding. I appreciate any feedback!

**Comment by jonkoops** [comment]
Unlike the `multiple` attribute these changes really don't add any new functionality to the inernals. So I'd argue that these tests should be sufficient.

Nice work!

**Comment by cowboyd** [comment]
Those tests were exactly what I was looking for. Mostly, I just want to prevent any accidental regressions on those attributes. :thumbsup:

**Comment by jonkoops** [comment]
I'll go ahead and close #11, since this pull request fixes that issue.

**Pull request merged**
