### PR TITLE
Ember form attribute binding (1.13.3)

### PR DESCRIPTION
**Pull request by Robdel12**
This adds form attr binding back. 

This version of Emberx-select can only run on ember 1.13.3 +!

### CODE REVIEW

**Comment by btecu** [comment]
Any ETA for the new release?

**Comment by Robdel12** [comment]
Probably around tomorrow. I want to get a blog post out about it since there will be compatibility issues for older ember users.

**Comment by lholmquist** [comment]
has this been released?

**Comment by btecu** [comment]
@lholmquist I ended up writing a component. It's not that much code to get a `<select>`.

**Pull request merged**
