### PR TITLE
Fix auto deploy on CI success / Update Ember-CLI

### PR DESCRIPTION
**Pull request by Robdel12**
## What is this?

This PR updates the CI deploy settings to fix two things:
- In my first stab at the circleci config I didn't properly setup the matrix to wait for all of the tests to run before trying to deploy
- Pagefront seems to be a dying hosting space. I switched over to using surge (which I use on my other OSS projects & love)

#### TODOs
- [x] Setup frontside surge account
- [x] Figure out why surge deploys hang on CI

### CODE REVIEW

**Comment by cowboyd** [comment]
Interesting. We tried updating `ember-surge` as indicated by @kiwiupover's in #208 But we're still getting it hanging. Oddly enough the command succeeds when we ssh into the box.

**Comment by Robdel12** [comment]
The only thing I can think of at this point is different ember-cli versions.

**Comment by cowboyd** [comment]
Node 9?

**Comment by kiwiupover** [comment]
@cowboyd have you talked to circleci about this. I can send a message if you to them if you have not. 

I will have them have a look at the this passing test run
https://circleci.com/gh/kiwiupover/ember-cli-spinjs/26

**Comment by cowboyd** [comment]
@kiwiupover I haven't had the time to send them. If you've dealt with this kind of problem before, then having you send a message might be more effective.

**Comment by Robdel12** [comment]
I think this might be an issue with surge? Or a combo of ember-cli & surge. Someone else mentioned they're having this issue on GitLab CI in https://github.com/kiwiupover/ember-cli-surge/issues/83#issuecomment-365539100

**Comment by kiwiupover** [comment]
@Robdel12 are you still looking at this.

**Comment by Robdel12** [comment]
@kiwiupover I am. I'm not sure how I feel about removing `JOBS: 2` from the circle config. Curious how that fixes this issue 🤔

**Comment by Robdel12** [comment]
@cowboyd to get this pushed over the finish line can you create an email for this? Something like `oss@frontside.io`? I'll use that email to sign up with surge & that will be the account that deploys.

**Pull request merged**
