### PR TITLE
Replace deprecated contains with includes

### PR DESCRIPTION
**Pull request by chrisccerami**

### CODE REVIEW

**Comment by Robdel12** [comment]
Thanks for the PR!

**Comment by gnapse** [comment]
Can this be included in a 2.x release as well? Right now is only available if using 3.0.0.

**Comment by chrisccerami** [comment]
I would also appreciate this being released in a 2.2.4 if possible.

**Comment by Robdel12** [comment]
I highly recommend upgrading & if you can't do that you can backport the fix for yourself (like https://github.com/efx/emberx-select/tree/backported-version-fix)

**Comment by chrisccerami** [comment]
Ok, thanks.

**Pull request merged**
