### PR TITLE
Calling the x-option component from a variable

### PR DESCRIPTION
**Pull request by aaronbhansen**
I want to enhance the template so I can pass in my own component name. This others to inherit from x-option and then specify the component they would like to use.

### CODE REVIEW

**Comment by aaronbhansen** [comment]
Possible to get this merged in?

**Comment by Robdel12** [comment]
Yeah! Sorry for the slow response. Could you add documentation to the readme about this? And a test would also be awesome :D

**Comment by cowboyd** [comment]
This is pretty interesting. I'm curious what the use-case is for needing to do this?

**Comment by aaronbhansen** [comment]
I needed to extend the select option to provide some extra functionality. By using a name dynamically I can do this
```
{{#x-select
    class="ui dropdown"
    value=value
    on-change=(action "update")
    optionComponentName="custom-xselect" as |xs|}}
  <option selected="selected" disabled="disabled">Select a Product</option>
  {{#each mappings_sorted as |content|}}
    {{xs.option
        value=content
        product_mapping=content
        order_selection=order_selection}}
  {{/each}}
{{/x-select}}
```

Then I can encapsulate all my changes on my own component that extends from x-option

**Comment by cowboyd** [comment]
> I needed to extend the select option to provide some extra functionality

Exactly. I'm curious what the extra functionality is that requires this approach. What are you trying to accomplish with your `x-option` subclass? If you could expand on it a bit, then we can maybe mull over the various options and make sure that either with this solution, or some other, you get that use-case taken care of.

**Comment by aaronbhansen** [comment]
The main use case was for the disabled attribute. It was 12 lines and depended on multiple properties and conditions based on the other dropdowns selected values. 
I probably could have gone the helper route, but I'd rather include the logic on the the component.

**Comment by cowboyd** [comment]
What I would do in this case would be to use a container component to clearly define the selection model, and then control the `x-select` explicitly.

```hbs
{{#selection-model mappings=mappings_sorted as |mappings|}}
  {{x-select value=value on-change=(action mappings.update) as |select|}}
    {{#each mappings as |mapping|}}
      {{select.option value=mapping.value disabled=mapping.disabled}}
        {{mapping.name}}
      {{/select.option}}
    {{/each}}
  {{/x-select}}
{{/selection-model}}
```

**Comment by aaronbhansen** [comment]
The problem is it doesn't just depend on the mapping, it depends on the combination of 
mapping, order selection, and current value. All of which can't come from a single property since they are separated. 
I could used a helper but that pulls the logic out of the component. Its also not as performance friendly since I would need to observe properties. 
`disabled=(should-disable mapping order_selection value)`

**Comment by cowboyd** [comment]
> The problem is it doesn't just depend on the mapping, it depends on the combination of
mapping, order selection, and current value. 

That's why you have the `mappings` model that computes all that for you. The suggestion isn't that it is a simple list of mappings, it is an enriched collection that contains all the properties you need, separated out into its own component.

In effect, it is the component you're seeking to write, but without its implementation co-mingled with x-select and x-option.

**Comment by aaronbhansen** [comment]
Yes I could go that route, but I'd prefer to have the logic encapsulated on the x-option component I plan to reuse in several places. I'm only providing a small glimpse of one of the use cases. I also have several default attributes I want on each x-option. Rather than add those same exact attributes each time I want them in the templates, I can put them on one extended x-option and re-use that everywhere. It doesn't make sense to repeat myself each time i want the same thing, when one x-option can have everything for reusability. 

I understand that you're trying to provide an alternative, but I don't see why it matters if I choose to encapsulate logic in an extended component or through an alternative like `mappings`. Having the component name being a variable doesn't change anything on the main x-select other than allowing others to choose either direction. They can either do it in `mappings` as you provided or extend x-option to keep their app DRY.

**Comment by cowboyd** [comment]
> I'm only providing a small glimpse of one of the use cases.

I believe you, and I believe that you have, in this PR, a working solution that accounts for those use-cases. But our job is to make sure that we fully understand a new pattern before baking it into the library because to do so means we're giving it tacit approval as a recommended way to solve problems. This is a pretty big change, and we can't do that job with just a glimpse.

It would really help to see the actual use cases, and why it can't be solved via any other means.

**Comment by aaronbhansen** [comment]
I'm not trying to be stubborn, but i don't know why more examples makes a difference. The api stays the exact same for everyone using it today, but allows an extension point for customization as shown in this ember conference video http://confreaks.tv/videos/emberconf2017-higher-order-components

It shouldn't matter if I choose to implement x-option like using specifically setting each attribute

```
x.option value=x disabled=y test=z classNames="red"
````

 or 

```
x-select componentName="custom"
  x.option value=x
```

I don't want anything different on the base component as exists today, I just want the flexibly to extend it without having to do a pull request in the future for custom functionality.

**Comment by aaronbhansen** [comment]
I was waiting to update the documentation and create a test before I received the final word on merging this in. Do you want me to do that or are you still deciding to merge in?

**Comment by cowboyd** [comment]
I'd say I'm still undecided on whether to merge this, and I feel like I don't have enough information to make the decision. I'm not philosophically opposed to it, but I still don't fully understand the ergonomics of extending components, which requires a change, vs composing them, which doesn't

**Comment by cowboyd** [comment]
Closing due to lack of context.

**Pull request closed without merging**
