### PR TITLE
Don't break when optionLabelPath is missing

### PR DESCRIPTION
**Pull request by tp**

### CODE REVIEW

**Comment by Robdel12** [comment]
Thanks for the PR! Can you write a test proving the bug?

**Comment by tp** [comment]
It's just the same as `optionValuePath`, which does not have a test either as far I can tell ;-)

Will check out your setup later and submit a test.

**Comment by tp** [comment]
Sorry, but I am new to Ember and testing it and did not quite figure out the steps required to add a new test in your current setup.

**Comment by Robdel12** [comment]
@tp No problem! This surfaced a lot more bugs for the blockless form.

**Pull request merged**
